Position/urls.py
from django.conf.urls import url

from .views import (
    PositionListView,
    PositionDetailView,
    PositionCreateView,
    PositionUpdateView,
    PresidentListView,
    VicePresidentListView,
)

urlpatterns = [
	url(r'^President/$', PresidentListView.as_view(), name='list'),
	url(r'^Vice-president/$', VicePresidentListView.as_view(), name='list'),
    url(r'^$', PositionListView.as_view(), name='list'),
    url(r'^create/$', PositionCreateView.as_view(), name='create'),
    # # slug
    #url(r'^(?P<slug>[\w-]+)/$', PositionDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/$', PositionUpdateView.as_view(), name='edit'),
]

Vote/urls.py
from django.conf.urls import url

from .views import (
    VoteYellowListView,
    VotePDPLabanListView,
    )

from PartyList.views import VotePartyListView

from Candidate.views import votes_counter

urlpatterns = [
    url(r'^$', VotePartyListView.as_view(), name='list'),
<<<<<<< HEAD
    url(r'^pdp-laban/$', VotePDPLabanListView.as_view(), name='list'),
    # url(r'^yellow-ribbon/$', VoteYellowListView.as_view(), name='list'),
    #url(r'^(?P<slug>[\w-]+)/$', VotePDPLabanListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', VoteYellowListView.as_view(), name='list'),
    url(r'^pdp-laban/(?P<slug>[\w-]+)/$', votes_counter, name='votes_counter'),
=======
    url(r'^yellow-ribbon/$', VoteYellowListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', VotePDPLabanListView.as_view(), name='list'),

>>>>>>> fc095d942ceb10280d603b86cf7b1b14b1054220
]

VotingSystem/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import reverse_lazy

from django.contrib.auth.views import(
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
    )

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^student/', include('Student.urls', namespace='student')),
    url(r'^course/', include('Course.urls', namespace='course')),
    url(r'^department/', include('Department.urls', namespace='department')),
    url(r'^candidate/', include('Candidate.urls', namespace='candidate')),
    url(r'^position/', include('Position.urls', namespace='position')),
    url(r'^partylist/', include('PartyList.urls', namespace='partylist')),

    # login
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^login/$', LoginView.as_view(template_name='registration/login.html'), name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),

    url(r'^password_change/$', PasswordChangeView.as_view(template_name='registration/password_change_form.html'),name='password_change'),
    url(r'^password_change/done/$', PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), name='password_change_done'),
    url(r'^password_reset/$', PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    url(r'^password_reset/done/$', PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    url(r'^reset/done/$', PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
]

Position/models.py
from django.db import models
from django.db.models.signals import pre_save

from Course.utils import unique_slug_generator

from django.core.urlresolvers import reverse

from django.conf import settings

User = settings.AUTH_USER_MODEL
# Create your models here.


class Position(models.Model):
	user 				= models.ForeignKey(User)
	position_name 		= models.CharField(max_length=200)
	timestamp			= models.DateTimeField(auto_now_add=True)
	updated				= models.DateTimeField(auto_now=True)
	slug				= models.SlugField(null=True, blank=True)

	def __str__(self):
		return self.position_name

	def get_absolute_url(self):
	  	return reverse('position:edit', kwargs={'slug': self.slug})

	@property
	def title(self):
	 	return self.position_name

def rl_pre_save_receiver(sender, instance, *arg, **kwargs):
	if not instance.slug:
		instance.slug = unique_slug_generator(instance)

pre_save.connect(rl_pre_save_receiver, sender=Position)

Position/forms.py
from django import forms


from .models import Position

class PositionDetailCreateForm(forms.ModelForm):
	class Meta:
		model = Position
		fields = [
			'position_name',
		]

Position/views.py
from django.shortcuts import render

from django.views.generic import (
	ListView, 
	DetailView, 
	CreateView, 
	UpdateView,
	View,
	)

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Position

from .forms import PositionDetailCreateForm

from Candidate.models import Candidate

# Create your views here.

class PositionListView(LoginRequiredMixin, ListView):
	def get_queryset(self):
		return Position.objects.filter(user=self.request.user)

class PositionDetailView(LoginRequiredMixin, DetailView):
	def get_queryset(self):
		return Position.objects.filter(user=self.request.user)

	def get_context_data(self, *args, **kwargs):
		candidate = Candidate.objects.all()
		context = {
			'candidate': candidate,
		}
		return render(request,"Position/detail-update",context)

class PresidentListView(ListView):
	queryset = Candidate.objects.filter(position__position_name__iexact = 'President')
	template_name = 'Position/president-list.html'

class VicePresidentListView(ListView):
 	queryset = Candidate.objects.filter(position__position_name__iexact = 'Vice president')
 	template_name = 'Position/vicepresident-list.html'

class PositionCreateView(LoginRequiredMixin, CreateView):
	form_class = PositionDetailCreateForm
	template_name = 'form.html'
	# success_url = "/student/"

	def form_valid(self, form):
		instance = form.save(commit=False)
		instance.user = self.request.user
		return super(PositionCreateView, self).form_valid(form)

	def get_context_data(self, *args, **kwargs):
		context = super(PositionCreateView, self).get_context_data(*args, **kwargs)
		context['position_name'] = 'Add Position'
		return context

class PositionUpdateView(LoginRequiredMixin, UpdateView):
	form_class = PositionDetailCreateForm
	template_name = 'Position/detail-update.html'

	
	def get_context_data(self, *args, **kwargs):
		context = super(PositionUpdateView, self).get_context_data(*args, **kwargs)
		position_name = self.get_object().position_name
		context['position_name'] = 'Update Position: {position_name}'
		return context

	def get_queryset(self):
		return Position.objects.filter(user=self.request.user)

Position/templates/Position/detail-update.html
{% extends "base.html" %}
{% block head_title %}{{ position.position_name }} | {{ block.super }}{% endblock %}
{% block content%}

<h4>Position Detail</h4>{% csrf_token %}
	<hr/>
	<h6> {{ position.position_name }}</h6>
	<hr/>
<h3>Make Changes</h3>
	{% include 'snippets/form-snippet.html' with form=form %}
{% endblock content%}

Position/templates/Position/position_detail.html
{% extends "base.html" %}
{% block head_title %}Position detail | {{ block.super }}{% endblock head_title %}
{% block content%}

<h4>Positions Detail</h4>
	<hr/>
	<h3>{{ position.position_name }}</h3>
	<p>Candidate :{{ position.candidate.student }} {{ position.candidate.student }}</p>
	<hr/>
{% endblock content%}

Position/templates/Position/position_list.html
{% extends "base.html" %}
{% block head_title %}List of Positions | {{ block.super }}{% endblock head_title %}
{% block content%}

<h4>List of Positions<small><a href='{% url "position:create" %}'> Add New</a></small></h4>

{% for obj in object_list %}
	<hr/>
	<h5><a href='{{ obj.get_absolute_url }}'>{{ obj.position_name }}</a></h5>
	{% empty %}
	<li><a href='{% url "position:create" %}'>Add One</a></li>
	<hr/>
{% endfor %}

{% endblock content%}

Position/templates/Position/president-list.html
{% extends "base.html" %}
{% block head_title %}Presidents | {{ block.super }}{% endblock head_title %}
{% block content%}

<h4>List of Presidents<small></small></h4>

{% for obj in object_list %}
	<hr/>
	<h5>{{ obj.position }}</h5>
	<h5>{{ obj.student }}</h5>
	<h5>{{ obj.party_list }}</h5>
	
{% endfor %}

{% endblock content%}

Position/templates/Position/vicepresident-list.html
{% extends "base.html" %}
{% block head_title %}Vice Presidents | {{ block.super }}{% endblock head_title %}
{% block content%}

<h4>List of Vice Presidents<small></small></h4>

{% for obj in object_list %}
	<hr/>
	<h5>{{ obj.position }}</h5>
	<h5>{{ obj.student }}</h5>
	<h5>{{ obj.party_list }}</h5>
	
{% endfor %}

{% endblock content%}